version: '3.9'
services:
  elosztott_rendszerek:
    container_name: elosztott_gyak
    build:
      context: .
      dockerfile: ./elosztott_gyak/Dockerfile
    ports:
      - "8080:80"
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
